name: Lint package
on:
  push:
    branches:
      - '*'

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.19.0'
      - run: npm ci
      - run: npm run lint
