name: Release package
on:
  push:
    branches:
      - master

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.19.0'
      - run: npm ci
      - run: npm run lint

  release:
    name: Release
    needs: [eslint]
    runs-on: ubuntu-latest
    env:
      BING_MAP_KEY: ${{ secrets.BING_MAP_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.19.0'
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: npm ci
      - run: npm i -g @quasar/cli
      - run: quasar build
      - run: rsync -e "ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" --delete -r ./dist/spa/ root@${{ secrets.SSH_HOST }}:${{ secrets.APP_SERVER_PATH }}
